### minimum docker version = 17.05.0+

ARG gccver=6
FROM gcc:${gccver}

RUN    apt-get update \
    && apt-get install -qq -y --fix-missing --no-install-recommends \
        cmake \
        libboost-dev \
        libboost-filesystem-dev \
        libboost-system-dev \
        libbz2-dev \
        libexpat1-dev \
        liblua5.2-dev \
        libluajit-5.1-dev \
        libpq-dev \
        libproj-dev \
        lua5.2 \
        make \
        postgresql-client \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

### ARG arg_OSM2PGSQL_VERSION=master
### ENV OSM2PGSQL_VERSION=${arg_OSM2PGSQL_VERSION}
### WORKDIR /openstreetmap
### RUN git clone --depth 1 --branch $OSM2PGSQL_VERSION https://github.com/openstreetmap/osm2pgsql.git

COPY . /openstreetmap/osm2pgsql

ARG arg_CXXFLAGS=" -Werror -fsanitize=address"
ENV CXXFLAGS=${arg_CXXFLAGS}

ARG arg_OSM2PGSQL_CMPARAMS="-DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DWITH_LUAJIT=OFF -DWITH_LUA=OFF "
ENV OSM2PGSQL_CMPARAMS=${arg_OSM2PGSQL_CMPARAMS}

WORKDIR /openstreetmap/osm2pgsql/build

RUN echo " ----- Last git HEAD       : " && git rev-parse HEAD
RUN echo " ----- Last git commit date: " && git log -1 --format=%cd 
RUN gcc -v
RUN cmake --version
RUN xml2-config --version
RUN lua -v
RUN dpkg -l | grep -E 'lua|proj|xml|bz2|pq|zlib|boost|expat'

# cmake
RUN cmake .. $OSM2PGSQL_CMPARAMS
# build
RUN make -j2

# run simple tests
ARG arg_RUNTEST="-L NoDB"
ENV RUNTEST=${arg_RUNTEST}

# RUN LSAN_OPTIONS=verbosity=1:log_threads=1 ctest -VV ${RUNTEST}
RUN make install
RUN osm2pgsql -V
