#!/bin/sh
#
# Remove any custom tablespaces we might have created.

BASEDIR=`pwd`

TBLDIR=${BASEDIR}/osm2pgsql-test-tablespace

if [ -d "$TBLDIR" ]; then
    find $TBLDIR -maxdepth 1 -mindepth 1 -type d -name 'PG*' -delete
fi
