TRUNCATE placex;
TRUNCATE search_name;
TRUNCATE place_addressline;
TRUNCATE location_point;
TRUNCATE location_point_26;
TRUNCATE location_point_25;
TRUNCATE location_point_24;
TRUNCATE location_point_23;
TRUNCATE location_point_22;
TRUNCATE location_point_21;
TRUNCATE location_point_20;
TRUNCATE location_point_19;
TRUNCATE location_point_18;
TRUNCATE location_point_17;
TRUNCATE location_point_16;
TRUNCATE location_point_15;
TRUNCATE location_point_14;
TRUNCATE location_point_13;
TRUNCATE location_point_12;
TRUNCATE location_point_11;
TRUNCATE location_point_10;
TRUNCATE location_point_9;
TRUNCATE location_point_8;
TRUNCATE location_point_7;
TRUNCATE location_point_6;
TRUNCATE location_point_5;
TRUNCATE location_point_4;
TRUNCATE location_point_3;
TRUNCATE location_point_2;
TRUNCATE location_point_1;
TRUNCATE location_area;

DROP SEQUENCE seq_place;
CREATE SEQUENCE seq_place start 1;

DROP SEQUENCE seq_progress_updates;
CREATE SEQUENCE seq_progress_updates start 1;

insert into placex select * from place where osm_type = 'N';
insert into placex select * from place where osm_type = 'W';
insert into placex select * from place where osm_type = 'R';
