.TH NODECACHEFILEREADER 1 "April 06, 2013"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
nodecachefilereader \- utility to inspect osm2pgsql's node cache.
.SH SYNOPSIS
.B nodecachefilereader
.RI /path/to/node.cache
.br
.B nodecachefilereader
.RI /path/to/node.cache\ node_id1\ node_id2\ node_id3
.br
.B nodecachefilereader
.RI /path/to/node.cache\ node_id1,node_id2,node_id3
.br
.SH DESCRIPTION
This manual page documents briefly the
.B nodecachefilereader
command.
.PP
.B nodecachefilereader
allows you to inspect and test osm2pgsql's custom node database.
.PP
.SH OPTIONS
If only the filename of the node cache is given, nodecachefilereader
performs some basic diagnostics on the node cache, as well as give
some basic benchmark results on how quickly it can lookup nodes by id
.PP
If one or more node_ids are given, nodecachefilereader retrieves the
information stored (latitude / longitude) about those nodes in the database
.PP
.SH SEE ALSO
.BR osm2pgsql (1),
.br
.SH AUTHOR
nodecachefilereader was written by Kai Krueger and other
OpenStreetMap project members.
.PP
